"""empty message

Revision ID: 71f5e6b07bea
Revises: 
Create Date: 2022-01-19 20:22:46.532492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f5e6b07bea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carro',
    sa.Column('create_time', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('montadora', sa.String(length=25), nullable=True),
    sa.Column('modelo', sa.String(length=25), nullable=True),
    sa.Column('ano', sa.Date(), nullable=True),
    sa.Column('quilometragem', sa.Float(), nullable=True),
    sa.Column('cor', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cupom',
    sa.Column('create_time', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descontoPercentual', sa.Float(), nullable=True),
    sa.Column('paraCarro', sa.Boolean(), nullable=True),
    sa.Column('paraMoto', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moto',
    sa.Column('create_time', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('montadora', sa.String(length=25), nullable=True),
    sa.Column('modelo', sa.String(length=25), nullable=True),
    sa.Column('ano', sa.Date(), nullable=True),
    sa.Column('quilometragem', sa.Float(), nullable=True),
    sa.Column('cor', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('create_time', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=70), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=True),
    sa.Column('endereco', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('carrinho',
    sa.Column('create_time', sa.String(), nullable=True),
    sa.Column('update_time', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('precoTotal', sa.Float(), nullable=True),
    sa.Column('quantidadeProdutos', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carrinho')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('moto')
    op.drop_table('cupom')
    op.drop_table('carro')
    # ### end Alembic commands ###
